name: "setup_cache"
description: "sets up the shared cache"
inputs:
  key:
    required: true
    description: "Cache key"
  restore_key:
    description: "Restore key when cache misses"

runs:
  using: "composite"
  steps:
    - name: Cache software caches
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
        key: ${{ inputs.key }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ inputs.restore_key != '' && inputs.restore_key || inputs.key }}

    - name: Cache conan
      uses: actions/cache@v4.0.2
      with:
        path: ~/.conan2/p
        key: ${{ inputs.key }}-${{ hashFiles('conanfile.py', 'conanfile.txt') }}
        restore-keys: |
          ${{ inputs.restore_key != '' && inputs.restore_key || inputs.key }}
