name: "setup_cache"
description: "sets up the shared cache"
inputs:
  key:
    required: true
    description: "Cache key"

runs:
  using: "composite"
  steps:
    - name: Cache software caches
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
        key: ${{ inputs.key }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ github.run_id }}
        restore-keys: |
          ${{ inputs.key }}-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Cache conan
      uses: actions/cache@v4.0.2
      with:
        path: ~/.conan2/p
        key: ${{ inputs.key }}-${{ hashFiles('conanfile.py', 'conanfile.txt') }}-${{ github.run_id }}
        restore-keys: |
          ${{ inputs.key }}-${{ hashFiles('conanfile.py', 'conanfile.txt') }}
